### ISSUE TITLE
ShortId

### ISSUE THREAD

**Issue by RohrerF** [ultimate-ttt/ultimate-ttt-backend#7]
We should create Ids shorter than GUIDs but unique enough.
Something like: PPBqWA9 ([dylang/shortid](https://github.com/dylang/shortid), this is not in C# though)

Implement in Domain -> ReadableIdGenerator.cs

**Comment by RohrerF** [comment]
maybe we can use [bolorundurowb/shortid](https://github.com/bolorundurowb/shortid)

**Comment by panmona** [comment]
I saw that package earlier. Didn't like the API on a first glance though. Not sure..

**Comment by RohrerF** [comment]
but we can take a look at how he generates ids and adopt it

**Comment by panmona** [comment]
```
        public static string Generate(bool useNumbers, bool useSpecial, int length)
        {
            if (length < 7)
            {
                throw new ArgumentException($"The specified length of {length} is less than the lower limit of 7.");
            }
            
            string __pool;
            Random rand;
            
            lock (threadLock)
            {
                __pool = _pool;
                rand = _random;
            }
            
            StringBuilder poolBuilder = new StringBuilder(__pool);
            if (useNumbers)
            {
                poolBuilder.Append(Numbers);
            }
            if (useSpecial)
            {
                poolBuilder.Append(Specials);
            }

            string pool = poolBuilder.ToString();
            
            char[] output = new char[length];
            for (int i = 0; i < length; i++)
            {
                int charIndex = rand.Next(0, pool.Length);
                output[i] =  pool[charIndex];
            }
            return new string(output);
        }
```

**Comment by RohrerF** [comment]
doesn't look to complicated. We can take this and implement adopt it to our needs

**Comment by RohrerF** [comment]
@maracuja-juice what do you think of id's containing only emojis? 

```
{
    "GameId": "🧙❤️🧁➕🍺"
    ...
}
```

**Comment by panmona** [comment]
I don't think that's feasible for the users 😂

**Comment by RohrerF** [comment]
Why not?

a) you can share the URL
b) you can search these 4/5 emojies on your keyboard.
c) just copy the id the other person sent you.
d) decide ID type (boring or with emojis)

**Comment by panmona** [comment]
I love how you changed from a "I don't understand emojies" person to a "Let's use emojies everywhere" person 😂

Seriously though:
a) If the user can decide if he wants to use emojies or not, then I'm fine with it.
b) Still it's not so easy to type these on a desktop.
c) And finding them on a mobile keyboard isn't that fast either.
d) Let's rather focus on the important stuff and start with "boring" ids first. We could add this option later.
